import { mkdir, readFile, readdir, writeFile } from "node:fs/promises";
import { dirname, join, posix, relative } from "node:path";
import { fileURLToPath } from "node:url";

import { compile } from "json-schema-to-typescript";

import { SCHEMA_ID_PREFIX } from "./canonical.js";

const ROOT = dirname(dirname(fileURLToPath(import.meta.url)));
const SCHEMA_DIR = join(ROOT, "schemas", "0.1.0");
const CORE_GENERATED_DIR = join(ROOT, "packages", "core", "src", "generated");
const VALIDATOR_GENERATED_DIR = join(ROOT, "packages", "validator", "src", "generated");

interface JsonSchemaDocument extends Record<string, unknown> {
  $id?: string;
  title?: string;
}

const TYPE_TARGETS = [
  { schema: "matter-record.schema.json", typeName: "MatterRecord", output: "matter-record.ts" },
  { schema: "event.schema.json", typeName: "OperationReceipt", output: "event.ts" },
  { schema: "manifest.schema.json", typeName: "BundleManifest", output: "manifest.ts" },
  { schema: "capability.schema.json", typeName: "Capability", output: "capability.ts" },
  { schema: "capability-set.schema.json", typeName: "CapabilitySet", output: "capability-set.ts" },
] as const;

const TYPE_BANNER = `/* eslint-disable */
/**
 * Generated from the normative MASA 0.1.0 JSON Schemas.
 * Do not edit this file. Run pnpm generate after changing schemas.
 */`;

async function main(): Promise<void> {
  await Promise.all([
    mkdir(CORE_GENERATED_DIR, { recursive: true }),
    mkdir(VALIDATOR_GENERATED_DIR, { recursive: true }),
  ]);
  const schemaFileNames = await listSchemaFiles(SCHEMA_DIR);
  const schemas = await Promise.all(
    schemaFileNames.map(async (fileName) => ({
      fileName,
      document: await readJsonSchema(join(SCHEMA_DIR, ...fileName.split("/"))),
    })),
  );

  ensureUniqueSchemaIds(schemas);

  for (const target of TYPE_TARGETS) {
    const source = schemas.find(({ fileName }) => fileName === target.schema);
    if (source === undefined) {
      throw new Error(`Required schema is missing: ${target.schema}`);
    }
    // json-schema-to-typescript prefers a schema's title/$id over the fallback
    // name argument. Give only the in-memory compilation copy a stable title;
    // the normative schema and its embedded validator copy remain untouched.
    const schemaForTypes = { ...source.document, title: target.typeName };
    const declaration = await compile(schemaForTypes, target.typeName, {
      bannerComment: TYPE_BANNER,
      cwd: SCHEMA_DIR,
      additionalProperties: false,
      declareExternallyReferenced: true,
      enableConstEnums: false,
      format: true,
      strictIndexSignatures: true,
      unknownAny: true,
    });
    await writeIfChanged(join(CORE_GENERATED_DIR, target.output), declaration);
  }

  await writeIfChanged(join(CORE_GENERATED_DIR, "index.ts"), generatedTypeIndex());
  await writeIfChanged(join(CORE_GENERATED_DIR, "protocol-resources.ts"), await generatedProtocolResources());
  await writeIfChanged(join(VALIDATOR_GENERATED_DIR, "schemas.ts"), generatedSchemaRegistry(schemas));
  await writeIfChanged(join(CORE_GENERATED_DIR, "ontology.ts"), await generatedRelationRegistry());
}

async function readJsonSchema(path: string): Promise<JsonSchemaDocument> {
  const source = await readFile(path, "utf8");
  const parsed = JSON.parse(source) as unknown;
  if (parsed === null || typeof parsed !== "object" || Array.isArray(parsed)) {
    throw new Error(`Schema is not a JSON object: ${relative(ROOT, path)}`);
  }
  const schema = parsed as JsonSchemaDocument;
  if (typeof schema.$id !== "string" || !schema.$id.startsWith(SCHEMA_ID_PREFIX)) {
    throw new Error(`Schema has no canonical MASA $id: ${relative(ROOT, path)}`);
  }
  return schema;
}

function ensureUniqueSchemaIds(
  schemas: readonly { fileName: string; document: JsonSchemaDocument }[],
): void {
  const ids = new Map<string, string>();
  for (const { fileName, document } of schemas) {
    const id = document.$id;
    if (id === undefined) {
      continue;
    }
    const previous = ids.get(id);
    if (previous !== undefined) {
      throw new Error(`Duplicate schema $id in ${previous} and ${fileName}`);
    }
    ids.set(id, fileName);
  }
}

function generatedTypeIndex(): string {
  return `${TYPE_BANNER}

export type { MatterRecord } from "./matter-record.js";
export type { OperationReceipt } from "./event.js";
export type { BundleManifest } from "./manifest.js";
export type { Capability } from "./capability.js";
export type { CapabilitySet } from "./capability-set.js";
`;
}

async function generatedProtocolResources(): Promise<string> {
  const resources = await Promise.all([
    {
      name: "masa-core",
      uri: "masa://spec/0.1.0/core",
      path: join(ROOT, "spec", "0.1.0", "core.md"),
      mimeType: "text/markdown",
    },
    {
      name: "masa-vocabulary",
      uri: "masa://spec/0.1.0/vocabulary",
      path: join(ROOT, "spec", "0.1.0", "vocabulary.md"),
      mimeType: "text/markdown",
    },
  ].map(async (resource) => ({
    name: resource.name,
    uri: resource.uri,
    mimeType: resource.mimeType,
    text: await readFile(resource.path, "utf8"),
  })));
  const capabilitySet = JSON.parse(
    await readFile(join(ROOT, "capabilities", "0.1.0", "reference.json"), "utf8"),
  ) as unknown;
  return `${TYPE_BANNER}

export const protocolResources = ${JSON.stringify(resources, null, 2)} as const;

export const referenceCapabilitySet = ${JSON.stringify(capabilitySet, null, 2)} as const;
`;
}

function generatedSchemaRegistry(
  schemas: readonly { fileName: string; document: JsonSchemaDocument }[],
): string {
  const entries = schemas.map(({ fileName, document }) => ({
    fileName,
    id: document.$id,
    document,
  }));
  const ids = Object.fromEntries(
    schemas.map(({ fileName, document }) => [schemaKey(fileName), document.$id]),
  );
  if (Object.keys(ids).length !== schemas.length) {
    throw new Error("Generated schema registry contains a duplicate schema key");
  }

  return `${TYPE_BANNER}

export interface EmbeddedSchema {
  fileName: string;
  id: string;
  document: Record<string, unknown>;
}

export const embeddedSchemas: readonly EmbeddedSchema[] = ${JSON.stringify(entries, null, 2)};

export const SCHEMA_IDS = ${JSON.stringify(ids, null, 2)} as const;

export function findEmbeddedSchema(id: string): EmbeddedSchema | undefined {
  return embeddedSchemas.find((schema) => schema.id === id);
}
`;
}

async function generatedRelationRegistry(): Promise<string> {
  const registryPath = join(ROOT, "ontology", "0.1.0", "relations.json");
  const source = await readFile(registryPath, "utf8");
  const parsed = JSON.parse(source) as {
    relations?: Array<{
      id?: unknown;
      acyclic?: unknown;
      inverse?: unknown;
      lineageDirection?: unknown;
    }>;
  };
  const orientations: Record<string, { canonicalPredicate: string; reverse: boolean }> = {};
  const lineageDirections: Record<string, "object-is-descendant" | "subject-is-descendant"> = {};
  const processed = new Set<string>();
  const acyclic: string[] = [];
  for (const relation of parsed.relations ?? []) {
    if (
      typeof relation.id === "string" &&
      (relation.lineageDirection === "object-is-descendant" ||
        relation.lineageDirection === "subject-is-descendant")
    ) {
      lineageDirections[relation.id] = relation.lineageDirection;
    }
    if (relation.acyclic !== true || typeof relation.id !== "string" || processed.has(relation.id)) {
      continue;
    }
    const inverse = typeof relation.inverse === "string" ? relation.inverse : undefined;
    orientations[relation.id] = { canonicalPredicate: relation.id, reverse: false };
    acyclic.push(relation.id);
    processed.add(relation.id);
    if (inverse !== undefined) {
      orientations[inverse] = { canonicalPredicate: relation.id, reverse: true };
      processed.add(inverse);
    }
  }
  acyclic.sort();

  return `${TYPE_BANNER}

export const relationRegistry = ${JSON.stringify(parsed, null, 2)} as const;

export const acyclicRelationPredicates: ReadonlySet<string> = new Set(${JSON.stringify(acyclic, null, 2)});

export const acyclicRelationOrientations: Readonly<Record<string, { canonicalPredicate: string; reverse: boolean }>> = ${JSON.stringify(orientations, null, 2)};

export const lineageRelationDirections: Readonly<Record<string, "object-is-descendant" | "subject-is-descendant">> = ${JSON.stringify(lineageDirections, null, 2)};
`;
}

function schemaKey(fileName: string): string {
  return fileName
    .replace(/\.schema\.json$/, "")
    .replace(/[\/-]([a-z])/g, (_match, letter: string) => letter.toUpperCase());
}

async function listSchemaFiles(directory: string, prefix = ""): Promise<string[]> {
  const entries = await readdir(directory, { withFileTypes: true });
  const files: string[] = [];
  for (const entry of entries.sort((left, right) => (left.name < right.name ? -1 : left.name > right.name ? 1 : 0))) {
    const relativeName = prefix === "" ? entry.name : posix.join(prefix, entry.name);
    if (entry.isDirectory()) {
      files.push(...(await listSchemaFiles(join(directory, entry.name), relativeName)));
    } else if (entry.isFile() && entry.name.endsWith(".schema.json")) {
      files.push(relativeName);
    }
  }
  return files.sort();
}

async function writeIfChanged(path: string, content: string): Promise<void> {
  let existing: string | undefined;
  try {
    existing = await readFile(path, "utf8");
  } catch {
    existing = undefined;
  }
  if (existing !== content) {
    await writeFile(path, content, "utf8");
  }
}

await main();
